### ISSUE TITLE
Phân công tìm hiểu testing tool

### ISSUE THREAD

**Issue by hieutt99** [hieutt99/aidudu#10]

**Comment by P3nt3st3r123** [comment]
@palizu bạn và mình cùng tìm hiểu về làm test-case tự động cho backend server bằng lib https://docs.pytest.org/en/6.2.x/ và front-end là https://jestjs.io/ nhé.
@tran-haison  và @haitt00 sẽ cùng tìm hiểu về manual test  ( cũng không có gì đâu vì chỉ là test tay, xem front-end ) 
test-sec: để sau cùng (hoặc có thể không có)

**Comment by P3nt3st3r123** [comment]
Còn phần làm test tự động sẽ bắt đầu với. test từng tính năng đơn rùi sau này sẽ làm test tổng hợp các tính năng đó -- càng ngày test sẽ càng chậm đó.

**Comment by P3nt3st3r123** [comment]
Quên mất về một số thư viện để test với các giao thức mà mình sẽ dùng: 
`http/https version 1.0->1.1`: https://pypi.org/project/requests/;https://docs.python-requests.org/en/latest/ --  (cũng khá dễ config, documents viết dễ hiểu và có nhiều code ví dụ)
`http/https version 2.0`: https://pypi.org/project/httpx/; https://www.python-httpx.org/http2/ -- (là lib mới (vì giao thức cũng mới) và được google index lên đầu khi search, nên tớ tin là tốt)
`mysql-connect`: https://pypi.org/project/mysqlclient/; https://readthedocs.org/projects/mysqlclient/ (lib này nhiêu project đã dùng, nhưng config trên window nó bị lỗi do phải có sdk của compiler C++ => down qua cái .whl https://www.lfd.uci.edu/~gohlke/pythonlibs/, nó đã được build trước rùi)
`PostgreSQL connect`: https://pypi.org/project/psycopg2/; https://www.psycopg.org/docs/ (lib này thì pip install là ok luôn)
`sqlite-db`: https://docs.python.org/3/library/sqlite3.html (nó là thư viện mặc đinh của python3 thì phải, pysqlite)

**Comment by P3nt3st3r123** [comment]
Tớ thấy có project testing support cả pytest và django.test ở đây và team mình có thể tham khảo nhá (tớ sẽ dựng automat test giống như trên này).
https://github.com/ptrstn/django-testing-examples
Lý do cần có tích hợp với django.test. Khi mình gõ commandline thế này là nó chạy test luôn. 
```
python mange.py test --tag=migration_test  # runs only migraion tests
python mange.py test --exclude-tag=migration_test  # runs all except migraion tests
```
(có thể sửa thành `unittest và  integration test`)
Rất tiện đúng không!

tham khảo thêm:
https://docs.djangoproject.com/en/3.2/topics/testing/overview/

**Comment by palizu** [comment]
test tự động t nghĩ dùng test của django là khá ổn và đủ rồi

**Comment by P3nt3st3r123** [comment]
Theo thống nhất hôm nay thì tụi mình sẽ dùng django.test -- có thể dùng thêm rest_framework.test vì nó kế thừa từ django.test nên có thể sẽ có hỗ trợ nhiều công cụ hơn.
Mình sẽ code theo class. Tên mỗi class sẽ tương ứng với 1 tính năng của API. Và tên method sẽ là loại test.
