### ISSUE TITLE
Học Django

### ISSUE THREAD

**Issue by minhdqdev** [hieutt99/aidudu#12]
Tài liệu tham khảo:
- Course YouTube: https://www.youtube.com/watch?v=UmljXZIypDc&ab_channel=CoreySchafer
- Sách: Django for Beginners (https://vn1lib.org/book/11235649/1e051e)
- Sách: Django for APIs (https://vn1lib.org/book/11235721/13b766)
- Sách: Django for Professionals

Cần hiểu ít nhất nội dung của 2 cuối đầu bao gồm các khái niệm sau: route, view, apiview, model
Bỏ qua phần template vì mình sử dụng React làm frontend, chỉ dùng Django để cấp API thôi.

Ai tìm hiểu xong APIView rồi có thể đọc tiếp APIViewSet.
Tham khảo: https://overcodedzz.github.io/handbook/computer%20science/django-viewset/

**Comment by minhdqdev** [comment]
@khoaLearnToCode, @palizu, @dangzed trong tuần này ưu tiên làm task này nhé

**Comment by minhdqdev** [comment]
Từng người báo lại tiến độ trong issue này luôn nhé, tuần tới mình sẽ bắt đầu viết API.

**Comment by dangzed** [comment]
đã đọc xong 2 cuốn

**Comment by palizu** [comment]
xong beginner đang đọc APIs

**Comment by haitt00** [comment]
đã đọc xong 2 cuốn

**Comment by khoapham2801** [comment]
Xong beginner. Đang đọc APIs

**Comment by minhdqdev** [comment]
ok, có vẻ hòm hòm rồi đấy. @khoaLearnToCode , @palizu , @P3nt3st3r123 đọc nốt trong milestone 3 nhé, tuần tới sẽ chia API để code nên mn tham khảo có thể tham khảo những API đc viết trước, dễ thôi.

@hieutt99 , @dangzed , @haitt00 mn đọc thêm về GenericViewSet, ModelViewSet của DRF nhé.

**Comment by minhdqdev** [comment]
Task này close nhé
