### ISSUE TITLE
Dựng docker-compose, dockerfile cho frontend

### ISSUE THREAD

**Issue by minhdqdev** [hieutt99/aidudu#25]
- Tạo file dockerfile, docker-compose để hot reload được

**Comment by minhdqdev** [comment]
Mn thử tìm hiểu xem có cách nào để reload khum nhé, đc thì nhàn cho team FE.

**Comment by dangzed** [comment]
reload là sao nhỉ

**Comment by minhdqdev** [comment]
> reload là sao nhỉ

Chạy react server ở dev mode, code đến đâu nó reload lại trang đến đấy. Trc t với Dũng có thử cơ mà chưa thành công tại vội quá. Ô hỏi thêm Dũng nhé.

**Comment by dangzed** [comment]
Done
