### ISSUE TITLE
Viết autotest-module và manual test

### ISSUE THREAD

**Issue by P3nt3st3r123** [hieutt99/aidudu#28]
Tớ sẽ viết trước rùi tụi mình đánh giá nhá.

**Comment by P3nt3st3r123** [comment]
![image](https://user-images.githubusercontent.com/60687432/142409176-6f57e169-dec2-43a7-a760-11cb643584dc.png)
Đây là phần mà tối nay tớ sẽ viết test thử nhá.

**Comment by P3nt3st3r123** [comment]
gồm chức năng auth/login, auth/refresh, auth/register. auth/forgot-password, /me => rùi sẽ viết luôn docs cho các endpoint này luôn.

**Comment by minhdqdev** [comment]
Cái này chắc ok rồi nhỉ, Sơn đóng issue này rồi chia nhỏ việc ra nhé

**Comment by P3nt3st3r123** [comment]
ok rùi nhé
