### ISSUE TITLE
Update API example & docs lên Postman

### ISSUE THREAD

**Issue by minhdqdev** [hieutt99/aidudu#43]
Mọi người viết API xong thì cập nhật Postman và gửi lại nhé, đồng thời test các api mình viết luôn.

Lưu ý mỗi API nên đi kèm example và doc. Ví dụ như 2 ảnh ở dưới
API cần ghi "(WIP)" ở cuối tên để team test còn biết.

**Comment by minhdqdev** [comment]
![image](https://user-images.githubusercontent.com/29064717/142765582-4377df4c-2942-490b-b0de-fa143f5c0688.png)

**Comment by minhdqdev** [comment]
![image](https://user-images.githubusercontent.com/29064717/142765607-1a321ec1-0d06-4b93-b260-2a3c76f740af.png)

**Comment by minhdqdev** [comment]
@hieutt99, @khoaLearnToCode, @palizu, @haitt00 cập nhật tiến độ nhé. Task này deadline cuối tuần

**Comment by khoapham2801** [comment]
Đã xong 3/4 APIs gồm Move all cards, Sort all cards in list, Archive a list. Còn API Copy a list chưa xong do cần các APIs CRUD liên quan.

**Comment by minhdqdev** [comment]
Còn @hieutt99 với @haitt00 chưa update postman phần workspace với board nhé. Đề nghị mn giải quyết dứt điểm để còn đóng issue.

**Comment by minhdqdev** [comment]
Task này done rồi nhé
