### ISSUE TITLE
viết testing api cho các endpoint /card /list /comments /checklistitem

### ISSUE THREAD

**Issue by P3nt3st3r123** [hieutt99/aidudu#45]
Dựa trên list-api postman và code test mẫu của tớ. Và cần hỏi bên develop phần đó đã hoàn chỉnh chưa. Để cậu có thể viết được code test nhá.

**Comment by palizu** [comment]
Đã test CRUD cho cards
add/remove member và label bị lỗi (có thể là chưa code xong)
@minhdq99hp review nhé

**Comment by P3nt3st3r123** [comment]
Yeap report @minhdq99hp  trong issue `report testcase` @palizu nhá

**Comment by P3nt3st3r123** [comment]
issue sẽ còn tồn tại đến khi feature chạy không bị lỗi nhá.

**Comment by P3nt3st3r123** [comment]
Thế này thì có khi cũng phải test chung với cả enpoint /list đó ông ơi! vì workspace => board => list => card

**Comment by P3nt3st3r123** [comment]
Vậy để test được card thì file setup mình cần có tạo: 
user (thuộc workspace) => xong rùi user đó tạo board (có 2 cách. 1 là mình sẽ mapping db-default và viết hết trong setUp(self), 2 là mỗi lần test sẽ phải gọi api lại. ) => rùi create lại quan hệ user của board-workspace (nếu dùng cách mapping-db để tạo data). => sau đó mới tạo được list các board => mới có từng card trong từng list

**Comment by P3nt3st3r123** [comment]
Đây là các enpoint của card 
![image](https://user-images.githubusercontent.com/60687432/143529091-192daa33-f8d4-409e-8970-1adcf4822d56.png)

**Comment by P3nt3st3r123** [comment]
thì cậu sẽ dùng hàm `reverse("name")`. Với những cái có params thì mình sẽ viết `reverse("name",args=[arg1, arg2])`

**Comment by P3nt3st3r123** [comment]
còn method nó xử lý thì hiện tại xem trên postman là ổn. Còn không thì sẽ đọc code ở view.py cũng hơi lung tung đấy.

**Comment by minhdqdev** [comment]
Feature nào lỗi thì ping cái đứa viết vào nhé

**Comment by P3nt3st3r123** [comment]
Ok tớ check code test của @palizu  thì ổn rùi nhá...

**Comment by palizu** [comment]
Ok để t viết tiếp test cho /lists

**Comment by palizu** [comment]
@hieutt99 Viết xong /cards api thì ping t ở đây nhé

**Comment by P3nt3st3r123** [comment]
ok

**Comment by palizu** [comment]
@P3nt3st3r123 review rồi merge vào branch test nhó

**Comment by P3nt3st3r123** [comment]
Ok

**Comment by P3nt3st3r123** [comment]
@palizu ơi! pull code branch testing mới về để test nhá. Vì vừa có code được merge từ `backend` vào nên có thể nhiều tính năng đã được fix đấy. -- hi vọng là tối nay test xong backend...

**Comment by P3nt3st3r123** [comment]
@palizu ơi! Tớ sẽ viết test phần /checklist nhé

**Comment by P3nt3st3r123** [comment]
Và @palizu làm nốt phần /checklistitem là tụi mình chờ kết thúc phần code test đó.

**Comment by hieutt99** [comment]
@palizu t update lại api rồi nhé

**Comment by palizu** [comment]
@P3nt3st3r123 @minhdq99hp test api đúng hết rồi đấy.
Xem xét close cái issue này dc rồi

**Comment by minhdqdev** [comment]
OK nhé
