### ISSUE TITLE
report testcase

### ISSUE THREAD

**Issue by P3nt3st3r123** [hieutt99/aidudu#47]
@admin.register(Card) # failed
class CardAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'name')

@admin.register(Comment) # failed
class CommentAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'name')

@admin.register(Checklist) # failed
class ChecklistAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'name')

@admin.register(ChecklistItem) # failed
class ChecklistItemAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'name')

Đang gây lỗi hê thống 
các endpoint khác 
auth-* Ok 
workspace-list Ok

**Comment by P3nt3st3r123** [comment]
Vãi hôm nay mới, ấn enter...

**Comment by P3nt3st3r123** [comment]
Report test case board :
board chạy Ok rùi nhé.

**Comment by P3nt3st3r123** [comment]
Ok @palizu viết report card testing nhá.

**Comment by minhdqdev** [comment]
@P3nt3st3r123 bổ sung labels, projects, milestones của các issue đi nhé

**Comment by P3nt3st3r123** [comment]
Đợi tới push bản test label nhé. -- Đăng chưa push bản code đó lên testing nên sẽ không pull về được. Cho nên, tớ copy luôn phần diff trên branch của đăng

**Comment by P3nt3st3r123** [comment]
Tính năng label-card của @dangzed pass nhé

**Comment by P3nt3st3r123** [comment]
/check_list tốt hết  nhá. (lỗi vì serialize chưa có __init__ nên không dùng put để update được ?)

**Comment by P3nt3st3r123** [comment]
@palizu còn những endpoint,tính năng nào chưa hoạt động đúng nhỉ để sửa WIP trên post man

**Comment by P3nt3st3r123** [comment]
VD: Phần /comment /checklsit_item còn tính năng nào hoạt động chưa đúng

**Comment by P3nt3st3r123** [comment]
Ok /comments /checklist_items chạy ngon rùi

**Comment by P3nt3st3r123** [comment]
còn mỗi tính năng copy a list của list trong /list bị lỗi @khoaLearnToCode ơi! Fix hộ mình nhá

**Comment by khoapham2801** [comment]
> còn mỗi tính năng copy a list của list trong /list bị lỗi @khoaLearnToCode ơi! Fix hộ mình nhá

muốn copy list thì cần API create checklist của @palizu .

**Comment by P3nt3st3r123** [comment]
@khoaLearnToCode ơi! @palizu có tính năng đó rùi nhá. -- test Ok luôn. Cậu có thể pull code mới nhất để hoàn thành nhá. -- merge từ develop về là chạy ngon.

**Comment by P3nt3st3r123** [comment]
@minhdq99hp đã cập nhật put => patch cho các test case được update. tính năng copy_list đã chạy đúng hành vi

**Comment by P3nt3st3r123** [comment]
Nếu có thêm tính năng mới sẽ được mở ở issue mới!
