### ISSUE TITLE
Design database diagram

### ISSUE THREAD

**Issue by hieutt99** [hieutt99/aidudu#5]
- dbdiagram
- hạn 1 tuần từ buổi họp 2

**Comment by minhdqdev** [comment]
Task này @khoaLearnToCode và @palizu làm nhé, lấy trên mạng rồi tạo lại trong dbdiagram.io hay tool gì đấy thì tuỳ, nên là dbdiagram.io.

Thứ 4 (3/11) thì 4 thg ngồi review lại một chút là đc. Rồi t với thg Hiếu dựng model trên django.
