### ISSUE TITLE
Design interface

### ISSUE THREAD

**Issue by hieutt99** [hieutt99/aidudu#6]
- using figma
- metronic themes
- 1 tuần từ sau buổi họp 2

**Comment by tran-haison** [comment]
@lehoangtran289 Đã làm chưa, gửi link figma đây làm zới

**Comment by minhdqdev** [comment]
Figma + Code của Metronic nhé: https://drive.google.com/file/d/12H_KtEyxR9rbS3QPCDVdn7NcYLS3WYa-/view?usp=sharing

**Comment by lehoangtran289** [comment]
Link prj figma: https://www.figma.com/files/project/41924587/Team-project?fuid=1037008194992594797
