### ISSUE TITLE
Thêm thông tin admin trong response api get workspace 

### ISSUE THREAD

**Issue by lehoangtran289** [hieutt99/aidudu#76]
![image](https://user-images.githubusercontent.com/56795731/145207669-2a13a4af-2a6d-4df2-bf39-40c5f285e99b.png)
Thêm thông tin về user_id của admin trong workspace

**Comment by haitt00** [comment]
Đã sửa lại API
<img width="693" alt="Screen Shot 2021-12-09 at 13 48 58" src="https://user-images.githubusercontent.com/54594085/145588513-caddd96d-6222-4290-919a-8bed1c94f845.png">
<img width="685" alt="Screen Shot 2021-12-09 at 13 49 21" src="https://user-images.githubusercontent.com/54594085/145588527-1c05cbc5-d044-4c1d-a4ae-f240ce976924.png">
